image: docker:git

services:
- docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CI_REGISTRY: "https://registry.gitlab.com"
  CONTAINER_IMAGE: registry.gitlab.com/Dourai1/DockerAssignment

before_script:
  - docker login -u $Dourai1 -p $FiveThirteen2001 $CI_REGISTRY
stages:
  - build and stage

job 1:
  stage: build and stage
  script:
   - docker build -t $CONTAINER_IMAGE:$CI_COMMIT_SHA .
   - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA